/*
 * File: app/view/Dashboard.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.Dashboard', {
    extend: 'Ext.Container',
    alias: 'widget.dashboard',

    config: {
        cls: 'dashboard-input',
        layout: {
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                cls: [
                    'dashboard-toolbar',
                    'top-toolbar'
                ],
                docked: 'top',
                title: '<p>Dashboard</p>',
                items: [
                    {
                        xtype: 'button',
                        cls: 'handlebutton'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        cls: 'userbutton'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'formpanellearner',
                margin: 0,
                style: 'padding-bottom:50px',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'panel',
                        cls: 'jklm',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'learnerpanel-user',
                                docked: 'left',
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'learnerdriver',
                                        docked: 'top',
                                        html: '<p>Learner Driver</p>',
                                        style: 'background:#406d96'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'learnerimage-driving',
                                        docked: 'bottom',
                                        html: '<p>Samuel Brown</p>',
                                        layout: {
                                            type: 'hbox'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'learnerpanel',
                                docked: 'right',
                                style: 'background: #216099',
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'learnerdriver',
                                        docked: 'top',
                                        html: '<p>Total Trips</p>',
                                        style: 'background:#355471'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'number-32',
                                        html: '<p>32</p>'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        cls: 'label-total-time',
                        html: '<h1>Total Driving Time</h1>',
                        style: 'background:#416d95'
                    },
                    {
                        xtype: 'panel',
                        cls: 'pan_driving_time',
                        style: 'background:#5ca7eb',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'pin-input-panel',
                                docked: 'top',
                                layout: {
                                    align: 'end',
                                    pack: 'center',
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: 'pin-input-panel-number',
                                        html: '<p>0</p>'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'pin-input-panel-number',
                                        html: '<p>1</p>'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'pin-input-panel-number',
                                        html: '<p>9</p>'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'pin-input-panel-number',
                                        html: '<p>4</p>'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'pin-input-panel-number',
                                        html: '<p>8</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'sun-panel',
                                docked: 'left',
                                html: '<p style="letter-spacing: 1px;padding-left:30px;padding-top:11px;font-weight:bold;font-size: 18px; line-height: 20px;color:#072641;"><span class="text-pan" ></span> 18h  :  28m</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'moon-panel',
                                docked: 'right',
                                html: '<p style="letter-spacing: 1px;padding-left:14px;font-size: 18px; line-height: 17px;padding-top:13px;font-weight:bold;color:#fff;"><span class="text-pan"></span> 07h  :  20m</p>'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'mkl',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'learnerpanel',
                                docked: 'left',
                                style: 'background:#216099',
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'learnerdriver-time',
                                        docked: 'top',
                                        html: '<p>Time Remaining</p>',
                                        style: 'background:#355471'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'learnerimage',
                                        html: '<h1>100<sup style="font-size:19px;line-height:41px;">h</sup></h1>',
                                        layout: {
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: 'label-learnerimage',
                                                docked: 'bottom',
                                                html: '<p>12<sup style="font-size:13px;line-height:20px; padding-left:2px;">m</sup></p>'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'learnerpanel-raincloud',
                                docked: 'right',
                                layout: {
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'learnerdriver',
                                        docked: 'top',
                                        html: '<p>Current Conditions</p>',
                                        style: 'background:#406d96'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'traffic-panel-rain',
                                        docked: 'bottom',
                                        html: '<p style="padding-left:37px;font-size:15px;color:#072641;padding-top:8px;"><span class="text-pan" style="margin-left: 83px; position: absolute;"></span>Light Traffic</p>'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});