/*
 * File: app/view/LdriverView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.LdriverView', {
    extend: 'Ext.Container',
    alias: 'widget.ldriverview',

    config: {
        cls: 'l-driver-container',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'panel',
                cls: 'l-driver-panel',
                html: '<p>See this feature in the</br>   full version of L-Driver.</p><p style="line-height: 63px;padding-right:6px;font-weight:bold;"> Coming Soon</p>',
                layout: {
                    type: 'hbox'
                }
            }
        ]
    }

});