/*
 * File: app/view/MytripView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.MytripView', {
    extend: 'Ext.Container',
    alias: 'widget.mytripview',

    config: {
        cls: 'mytrip_container',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'toolbar',
                cls: 'mytrip_titlebar',
                docked: 'top',
                title: '<p>My Trips</p>',
                items: [
                    {
                        xtype: 'button',
                        cls: 'handlebutton'
                    }
                ]
            },
            {
                xtype: 'list',
                name: 'triplist',
                flex: 1,
                cls: 'triplist',
                id: 'triplist',
                scrollable: 'vertical',
                itemTpl: [
                    '<tpl if="isNight(date)">',
                    '    <div class="trip-list night">',
                    '<tpl else>',
                    '    <div class="trip-list day">',
                    '</tpl>',
                    '    <div class="left"><p>{[getFormattedDateOnly(values.date)]}</p></div>',
                    '    <div class="right"><p><span class="trip_span"><tpl if="time">{time}min</tpl></span>{title}</p></div>',
                    '</div>'
                ],
                store: 'mytripstore',
                grouped: true,
                onItemDisclosure: true
            }
        ]
    }

});