/*
 * File: app/view/NewtripView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.NewtripView', {
    extend: 'Ext.Container',
    alias: 'widget.newtripview',

    config: {
        cls: 'newtrip_view',
        layout: {
            type: 'vbox'
        },
        scrollable: 'vertical',
        items: [
            {
                xtype: 'toolbar',
                cls: [
                    'newtrip_titlebar',
                    'top-toolbar'
                ],
                docked: 'top',
                title: '<p style="margin-top:-1px;">New Trip</p>',
                items: [
                    {
                        xtype: 'button',
                        name: 'handle-button',
                        cls: 'handlebutton',
                        margin: 0
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        cls: 'newtrip_button',
                        text: '<p class="cancel">Cancel</p>'
                    }
                ]
            },
            {
                xtype: 'panel',
                name: 'newtriplistpanel',
                cls: 'menuP_panel',
                style: 'padding-bottom:90px',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_first_panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'home-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                hidden: false,
                                html: '<p class="firsttext-span" style="background:#e6f2fd;color:#3892e3"><span class="lasttext-span" style="color:#000; font-size:15px;">Richmond</span>Start Location</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_second_panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'map-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                hidden: false,
                                html: '<p class="firsttext-span" style="background:#effbe0;color:#5aa602"><span class="lasttext-span" style="color:#000;">Balwyn</span>Destination</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_third_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'car-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                hidden: false,
                                html: '<p class="firsttext-span" style="background:#fff0e6;color:#fb6e17"><span class="lasttext-span" style="color:#000;">Dad\'s Club Sport</span>Vehicle</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'home_first_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'parking-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#e6f2fd;color:#3892e3"><span class="lasttext-span" style="color:#000;"></span>Parking</p>'
                            },
                            {
                                xtype: 'panel',
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'togglefield',
                                        cls: [
                                            'toggle-field',
                                            'toggle-field-first'
                                        ],
                                        zIndex: 10
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_second_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'traffic-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#effbe0;color:#5aa602"><span class="lasttext-span" style="color:#000;">Moderate</span>Traffic</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'home_third_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'weather-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#fff0e6;color:#fb6e17"><span class="lasttext-span" style="color:#000;"></span>Weather</p>'
                            },
                            {
                                xtype: 'panel',
                                hidden: false,
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'vbox'
                                },
                                items: [
                                    {
                                        xtype: 'togglefield',
                                        cls: [
                                            'toggle-field-second',
                                            'toggle-field'
                                        ],
                                        zIndex: 10
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_first_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'road-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#e6f2fd;color:#3892e3"><span class="lasttext-span" style="color:#000;">Inner City</span>Road</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_second_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'time-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#effbe0;color:#5aa602"><span class="lasttext-span" style="color:#000;">Dawn/Dusk</span>Time of Day</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_third_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'odometer-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#fff0e6;color:#fb6e17"><span class="lasttext-span" style="color:#000;">58703 km</span>Odometer</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        name: 'drivelistitem',
                        cls: 'home_first_panel',
                        hidden: false,
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'supervisor-panel-image',
                                    'list-image'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label',
                                html: '<p class="firsttext-span" style="background:#e6f2fd;color:#3892e3"><span class="lasttext-span" style="color:#000;">Ronald Brown</span>Supervisor</p>'
                            },
                            {
                                xtype: 'panel',
                                cls: 'discloser-image'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});