/*
 * File: app/view/SignupView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.SignupView', {
    extend: 'Ext.Container',
    alias: 'widget.signupview',

    config: {
        cls: 'parentabcd',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'panel',
                flex: 1,
                cls: 'singup-panel',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'signup-button',
                        right: 0,
                        text: 'Sign Up'
                    },
                    {
                        xtype: 'formpanel',
                        cls: 'formpaneltext',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: false,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: 'form-text-field',
                                placeHolder: 'Username  '
                            },
                            {
                                xtype: 'textfield',
                                cls: 'form-text-field',
                                placeHolder: 'Password'
                            },
                            {
                                xtype: 'button',
                                name: 'loginbutton',
                                cls: 'tick-buttonimage'
                            },
                            {
                                xtype: 'button',
                                name: 'facebookbutton',
                                cls: 'facebookbutton',
                                html: '<p>Sign in via Facebook</p>'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});