/*
 * File: app/view/TripsummaryView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.view.TripsummaryView', {
    extend: 'Ext.Container',
    alias: 'widget.tripsummaryview',

    config: {
        cls: 'closetrip',
        style: 'background:#fff;',
        layout: {
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                cls: [
                    'tripsummary_titlebar',
                    'top-toolbar'
                ],
                docked: 'top',
                title: '<p style="margin-top:-1px;">Trip Summary</p>',
                items: [
                    {
                        xtype: 'button',
                        name: 'handle-button',
                        cls: 'handlebutton',
                        margin: 0
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        name: 'tripdetailscancel',
                        cls: 'newtrip_button',
                        text: '<p class="cancel">Cancel</p>'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                cls: 'summary-trip-panel',
                layout: {
                    type: 'vbox'
                },
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'panel',
                        cls: 'trip_summary_date-panel',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'trip_summary_date-panel-text',
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: 'trip-calendar-image',
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'trip-summary-date-text',
                                        html: '<p>September 9th, 2013</p>'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'trip-summary-time-counter',
                        html: '<h1>00:00</h1>',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'trip-summary-time-counter-min-hour',
                                html: '<p class="trip-min"><span class="trip-hour">minutes</span>hours</p>'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'googlemap-trip-panel',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'map',
                                name: 'map',
                                cls: 'googlemap-trip'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'trip-image-panel',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image-map',
                                            'trip-panel-image'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Richmond to Balwyn</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-car'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Dad’s Club Sport</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-parking'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Parking Practice</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-traffic'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Heavy Traffic</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-weather'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Light Rain</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-road'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Inner City</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-clock'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>Dawn / Dusk</p>'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'trip-images-panel-home',
                                hidden: false,
                                layout: {
                                    type: 'hbox'
                                },
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'trip-panel-image',
                                            'trip-panel-image-odometer'
                                        ],
                                        layout: {
                                            type: 'vbox'
                                        }
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        cls: 'home-label-trip',
                                        html: '<p>58712 KM</p>'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'trip-images-panel-home-supervisor',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'trip-panel-image',
                                    'trip-panel-image-supervisor'
                                ],
                                layout: {
                                    type: 'vbox'
                                }
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                cls: 'home-label-trip-supervisor',
                                html: '<p>Supervised By</p>'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'summary-box-panel',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'supervisor-box-panel',
                                layout: {
                                    align: 'center',
                                    pack: 'center',
                                    type: 'hbox'
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }

});