/*
 * File: app/model/MyTripModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.model.MyTripModel', {
    extend: 'Ext.data.Model',
    alias: 'model.mytripmodel',

    config: {
        fields: [
            {
                name: 'date',
                type: 'string'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'time',
                type: 'int'
            },
            {
                name: 'vehicle',
                type: 'string'
            },
            {
                name: 'parking',
                type: 'string'
            },
            {
                name: 'traffic',
                type: 'string'
            },
            {
                name: 'weather',
                type: 'string'
            },
            {
                name: 'location',
                type: 'string'
            },
            {
                name: 'distance',
                type: 'int'
            },
            {
                name: 'supervisor',
                type: 'string'
            },
            {
                name: 'gps'
            }
        ]
    }
});