/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ldriver.controller.LoginController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.logincontroller',

    config: {
        refs: {
            main: {
                autoCreate: true,
                selector: 'main',
                xtype: 'main'
            },
            dashboard: 'dashboard',
            loginbutton: 'button[name=loginbutton]'
        },

        control: {
            "loginbutton": {
                tap: 'onloginButtonTap'
            }
        }
    },

    onloginButtonTap: function(button, e, eOpts) {
        var main = this.getMain();

        /*Ext.Viewport.animateActiveItem(main, {
        type: 'slide',
        direction: 'left'
        });*/

        Ext.Viewport.getLayout().setAnimation({
            type: 'slide',
            direction: 'left'
        });
        Ext.Viewport.setActiveItem(main);
    }

});